// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoHVfz70_ukmLN1IBYU3mzbNaJtuSyjXI',
    appId: '1:584918864877:web:b88fc5d4a0f93ecd998de4',
    messagingSenderId: '584918864877',
    projectId: 'dicoding-expert-submissi-1c649',
    authDomain: 'dicoding-expert-submissi-1c649.firebaseapp.com',
    storageBucket: 'dicoding-expert-submissi-1c649.firebasestorage.app',
    measurementId: 'G-DSGCWNMWG1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeqETVxLn7MAlPNkJTFjt7UwKvAVoHNzw',
    appId: '1:584918864877:android:2a87843cce596fdd998de4',
    messagingSenderId: '584918864877',
    projectId: 'dicoding-expert-submissi-1c649',
    storageBucket: 'dicoding-expert-submissi-1c649.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEkoS3LAwsaKQ1UmowqVsfu4aDwjpeunM',
    appId: '1:584918864877:ios:70cf949a81c08f1c998de4',
    messagingSenderId: '584918864877',
    projectId: 'dicoding-expert-submissi-1c649',
    storageBucket: 'dicoding-expert-submissi-1c649.firebasestorage.app',
    iosBundleId: 'com.dicoding.ditonton',
  );
}
